tools:
    php_code_coverage:
        test_command: "phpunit --configuration tests/phpunit.xml"
        filter:
            paths: ["lib/*"]
    php_sim:
        enabled: true
        filter:
            paths: ["lib/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["lib/*"]
    php_pdepend:
        enabled: true
        filter:
            paths: ["lib/*"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["lib/*"]
